# Generated by Django 4.0.2 on 2022-02-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('Uni', 'unisex')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
