# Generated by Django 4.0.2 on 2022-02-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_product_delete_shoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_posted',
            new_name='created',
        ),
    ]
